### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by exvertus**

### CODE REVIEW

**Review by apkatsikas — APPROVED** [review]

**Comment by apkatsikas** [comment]
it would be nice to remove the package-lock changes since we arent updating dependencies. ive created this PR to hopefully fix this file from diffing depending on environment https://github.com/apkatsikas/darnbot/pull/18

**Comment by exvertus** [comment]
@apkatsikas should be good now

**Comment by apkatsikas** [comment]
> @apkatsikas should be good now

can you try switching your node version locally and re-run `npm i` ? i would expect the result to make package-lock.json the same version as what is in main. or maybe just revert your package-lock.json changes.

**Comment by exvertus** [comment]
> > @apkatsikas should be good now
> 
> can you try switching your node version locally and re-run `npm i` ? i would expect the result to make package-lock.json the same version as what is in main. or maybe just revert your package-lock.json changes.

I tried installing nvm and running the ps1 script but it didn't seem to make a difference, even after I did the install after nvm use 12.16.3.

**Comment by exvertus** [comment]
> > > @apkatsikas should be good now
> > 
> > 
> > can you try switching your node version locally and re-run `npm i` ? i would expect the result to make package-lock.json the same version as what is in main. or maybe just revert your package-lock.json changes.
> 
> I tried installing nvm and running the ps1 script but it didn't seem to make a difference, even after I did the install after nvm use 12.16.3.

I can just keep using the container and delete the code changes from the lock file, but other machines might run into the same issue if nvm and the ps1 script didn't fix things on mine.

**Comment by exvertus** [comment]
Should be all set now. I might get the same thing if I try a local build again but I'll just use docker so the lock file gets built into the container. Just an FYI that someone else's machine might fuck with the lock file again even if they use nvm.

**Comment by apkatsikas** [comment]
> > > > @apkatsikas should be good now
> > > 
> > > 
> > > can you try switching your node version locally and re-run `npm i` ? i would expect the result to make package-lock.json the same version as what is in main. or maybe just revert your package-lock.json changes.
> > 
> > 
> > I tried installing nvm and running the ps1 script but it didn't seem to make a difference, even after I did the install after nvm use 12.16.3.
> 
> I can just keep using the container and delete the code changes from the lock file, but other machines might run into the same issue if nvm and the ps1 script didn't fix things on mine.

weird, this also could be an npm version thing, vs a node version thing. in which case we might just have to accept discrepancies or somehow try to control npm version, but that seems excessive. lets keep an eye on it, my goal is mostly just to understand why its happening more than anything

**Comment by exvertus** [comment]
> > > > > @apkatsikas should be good now
> > > > 
> > > > 
> > > > can you try switching your node version locally and re-run `npm i` ? i would expect the result to make package-lock.json the same version as what is in main. or maybe just revert your package-lock.json changes.
> > > 
> > > 
> > > I tried installing nvm and running the ps1 script but it didn't seem to make a difference, even after I did the install after nvm use 12.16.3.
> > 
> > 
> > I can just keep using the container and delete the code changes from the lock file, but other machines might run into the same issue if nvm and the ps1 script didn't fix things on mine.
> 
> weird, this also could be an npm version thing, vs a node version thing. in which case we might just have to accept discrepancies or somehow try to control npm version, but that seems excessive. lets keep an eye on it, my goal is mostly just to understand why its happening more than anything

Word I think Mat had the other client that kept thrashing this file so if his still he'll probably want to start using docker too

**Pull request merged**
