### PR TITLE
Help

### PR DESCRIPTION
**Pull request by mat-lundin**
Added basic help function for people who can't see the code and might not remember the commands.

### CODE REVIEW

**Comment by apkatsikas** [comment]
proud of ya!

**Comment by apkatsikas** [comment]
run `npm fix lint` and commit the result. should fix your double quotes among other issues. you may need to `npm install` in the repo if you havent updated since i added the linter

**Comment by mat-lundin** [comment]
1. sorry, i prefer single quotes anyway not sure why i did double quotes
2. do i just run that in my branch? or since it's a package (?) it doesn't matter
3. will it be obvious which file(s) to commit once I run that?

**Review by apkatsikas — COMMENTED** [review]
> 1. sorry, i prefer single quotes anyway not sure why i did double quotes
> 2. do i just run that in my branch? or since it's a package (?) it doesn't matter
> 3. will it be obvious which file(s) to commit once I run that?

1. no problem! 
2. yeah just run it in the darnbot directory while your branch is checked out
3. you can run `git status` to see which files are changed after running `npm run fixlint`. You can also always say `git add .` which stages all changed files in the repo so you can then `git commit -m "i did some stuff"`

**Comment by mat-lundin** [comment]
Merged Drew's changes

Going investigate replacing the filter with the find function before we merge this bad boy to Main

**Review by exvertus — APPROVED** [review]
The testing the help cmd from my windows machine worked

**Pull request merged**
